### ISSUE TITLE
Refactor unstructured scheme tests

### ISSUE THREAD

**Issue by stephenworsley** [SciTools-incubator/iris-esmf-regrid#116]
## 📰 Custom Issue

The structure of tests in tests.unit.experimental.unstructured_scheme (in the unstructured_scheme feature branch) is currently messy. Especially with respect to helper functions such as `_grid_cube` which exists in `test__cube_to_GridInfo` and `_flat_mesh_cube` which exists in `test__regrid_unstructured_to_rectilinear__prepare`. After a refactor, these should exist in a common place. It is also worth investigating to what extent pytest fixtures can improve the structure of the tests.

**Comment by trexfeathers** [comment]
I still think this is an issue to address
