### ISSUE TITLE
Rudimentary docs

### ISSUE THREAD

**Issue by jonseddon** [SciTools-incubator/iris-esmf-regrid#139]
## ✨ Feature Request
Rudimentary docs 

## Motivation
It would be useful to have some very basic docs to show how to install iris-esmf-regrid (I guess just conda or pip install) and how to do a very basic regrid please. That should be enough to get started and the rest can be understood from the source.

## Additional context

<details>
<summary>Click to expand <b>this section...</b></summary>

As suggested in scitools/iris#4463
</details>

**Comment by schlunma** [comment]
In addition, a small table of all currently implemented regridders would be nice :+1:
