### ISSUE TITLE
Drop support for python 3.6

### ISSUE THREAD

**Issue by jamesp** [SciTools-incubator/iris-esmf-regrid#149]
* Iris 3.1 dropped support for python <3.7.
* Iris 3.2 drops support for python <3.8.

This project should probably also move it's minimum requirement to one of these two options.

Edit: Fixed python version numbers

**Comment by jamesp** [comment]
@valeriupredoi thanks, I got that totally wrong!! What I meant was iris 3.2 drops support for python < 3.8. Doh. Thanks for picking up

**Comment by valeriupredoi** [comment]
ah beautiful then! We were already scartching our heads how to get around the iris support drop for Python=3.9 :grin:
