### ISSUE TITLE
Review the API docstrings

### ISSUE THREAD

**Issue by pp-mo** [SciTools-incubator/iris-esmf-regrid#158]
## 📰 Custom Issue
Great to have the built API docs up.
But just roughly scanning, I reckon there is quite a bit in there that needs some attention / improvement.
For instance (in my personal views)..
  * [esmf_regrid.schemes.ESMFAreaWeighted](https://iris-esmf-regrid.readthedocs.io/en/latest/_api_generated/esmf_regrid.schemes.html#esmf_regrid.schemes.ESMFAreaWeighted)
     * I don't, personally, much fancy the use of the word "separated" for X and Y coords.  
       You could say that the coordinate system is "separable", but I'm not sure this gives the right impression directly.
       I think the best approach in the Iris docs is to focus on the dimensions : to say that X and Y coordinates have separate dimensions
  * [esmf_regrid.schemes.ESMFAreaWeightedRegridder](https://iris-esmf-regrid.readthedocs.io/en/latest/_api_generated/esmf_regrid.schemes.html#esmf_regrid.schemes.ESMFAreaWeightedRegridder)
    * It says "Regridder class for unstructured to rectilinear Cubes.", but this seems at odds with "src_cube – A rectilinear instance of Cube"

So, 
**I'd suggest this could do with thorough general review, when we can find time.**

I know from bitter experience (1) how _very_ hard is to precisely + clearly describe these different types of coordinate mappings, given that nearly all the recognised technical terms are used ambiguously in different contexts, and (2) how confused users are about these distinctions in the first place
So, it's always an uphill struggle to define terms clearly.  
But we can at least aim to be complete + consistent in our usage
-- which would at least be definite progress, since the existing Iris docs have made rather a mess of it !!

**Comment by trexfeathers** [comment]
We did make a lot of progress in #155, but not focused on the things mentioned here. Should this be kept open @pp-mo?
