### ISSUE TITLE
Enable Python 3.9 and 3.10

### ISSUE THREAD

**Issue by zklaus** [SciTools-incubator/iris-esmf-regrid#161]
## ✨ Feature Request

It would be great if we could get Python 3.9 and Python 3.10 builds for iris-esmf-regrid. At the moment, the maximum version is 3.8, but it is unclear to me whether that is simply because that was the version available when the CI was setup or for a deeper reason.

Does anyone know?

**Comment by trexfeathers** [comment]
@zklaus we're currently held up by iris#4465, which is a barrier to advancing Iris (and therefore iris-esmf-regrid too) beyond 3.8.

**Comment by zklaus** [comment]
Thanks, @trexfeathers for the explanation. However, Iris itself doesn't seem to draw the same conclusion and installs happily in 3.9 and 3.10.

**Comment by trexfeathers** [comment]
@zklaus the problem is that we're unable to run Iris' test suite `>3.8`, so we therefore can't officially support `>3.8` ☹

**Comment by zklaus** [comment]
I understand. But nevertheless, iris installs in 3.9 and 3.10 environments, so I don't think that should be grounds for iris-esmf-regrid to forbid it.

**Comment by trexfeathers** [comment]
@stephenworsley thoughts?

**Comment by stephenworsley** [comment]
Since iris now has these requirements files, these can be added to iris-esmf-regrid without any problem.

**Comment by zklaus** [comment]
My understanding is that this was fixed with #208, right?

Thanks, @stephenworsley, @trexfeathers! :tada:

**Comment by stephenworsley** [comment]
Closed by #208
