### ISSUE TITLE
List and prioritise possible features for the project

### ISSUE THREAD

**Issue by stephenworsley** [SciTools-incubator/iris-esmf-regrid#2]
The purpose of this issue is to record and discus possible features we would want/need for this project and decide which are are necessary and which are desirable. 

Below is a categorised list of features, feel free to add more that I might have missed. Features which I think are optional I have marked with a "(?)".

Scope of support:

- Regridders will be exposed as Iris schemes. These schemes will be able to handle cubes with more dimensions than just the grid.
- Multiple ESMF RegridMethods will be supported including:
  - `CONSERVE`
  - `BILINEAR`
  - `NEAREST_STOD` (source to destination) (?)
- Rectilinear and curvilinear grids can be represented as ESMF grids to be regrid.
- Code will maintain flexibility to allow support for ESMF Meshes to be added easily.

Functionality of building the regridder:

- Any use of ESMF should be restricted to the building of the regridder and the built regridder should contain no ESMF objects. The built regridder should contain only Python objects and sparse matrices.
- The regridder should be "cachable". It should be possible to either save and load a regridder, or else to extract savable information and rebuild a regridder from that information.
- The regridder should be able to be built in an environment without ESMF using only cached information. (?)
- The building of the regridder should be able to be done (subgrids passed to ESMF) in chunks in order to save memory (and perhaps allow parallelisation). (?)

Functionality of the built regridder:
- The built regridder should be able to allow some form of multiprocessing (i.e. Dask).
- The built regridder should be able to handle masked data.
- It should be possible to choose between a regridder with a fixed mask or a flexible mask, one with a fixed mask will handle masking during the build step (and have improved performance), one with a flexible mask will handle masking after the build step.
- There should be an Iris style `mdtol` setting for conservative regridding.

**Comment by rockdoc** [comment]
As per our recent off-line conversation, I believe it would be beneficial if the new module/package being developed as part of this initiative could include the capability to perform regridding using a previously generated file of interpolation/regridding weights. Typically these weights are generated by a separate command-line utility, such as those provided by the SCRIP and ESMF packages. In principle, however, the weights might be computed in any number of different ways, though this would be largely immaterial to the iris-esmf-regrid package.

As regards the API, the function that performs weights-based regridding could read the weights from a number of sources, including but not limited to the following:

- specification of the path to the original weights file (invariably in netcdf format)
- via appropriate numpy arrays of grid cell indices and weights
- via appropriate sparse matrix objects (e.g. those defined by scipy)

The current metocean regridding software ecosystem uses a number of formats for storing weights files. Support for the SCRIP and ESMF formats would be essential. There are probably other formats that it would be desirable to support (e.g. that used by the OASIS coupler?)

**Comment by zklaus** [comment]
Just to add another use case for generic meshes: ESMValGroup/ESMValCore#751
