### ISSUE TITLE
ESMPy API change in v8.4.0

### ISSUE THREAD

**Issue by bouweandela** [SciTools-incubator/iris-esmf-regrid#227]
Note that starting with [ESMF 8.4.0, ESMPy should be imported with `import esmpy` instead of `import ESMF`](https://earthsystemmodeling.org/static/releases.html). This would make the current version incompatible with the latest version of ESMF unfortunately.

**Comment by zklaus** [comment]
As an aside, @bouweandela wrote a nifty little solution for ESMValTool that you might copy in ESMValGroup/ESMValCore#1876.

**Comment by pletzer** [comment]
This is also mentioned in #229

**Comment by valeriupredoi** [comment]
hey guys, this would be very nice to have since this also blocks support for Python 3.11 which would be nice to have also - if you want me to I can open a PR with it? :beer:

**Comment by valeriupredoi** [comment]
I am being goody two-shoes so I opened a PR :grin: https://github.com/SciTools-incubator/iris-esmf-regrid/pull/240

**Comment by valeriupredoi** [comment]
This was a good iisue, RIP good issue 😢 Also, this kind of auto-closer bot, like iris has one too, may be harmful, if a human is not checking what it closed
