### ISSUE TITLE
readthedocs build is failing

### ISSUE THREAD

**Issue by bjlittle** [SciTools-incubator/iris-esmf-regrid#251]
## 🐛 Bug Report

The `readthedocs` build has been failing since the last 3 months, we should:

- [x] fix this
- [x] add a RDT badge to the `README.md` so that it easily alerts developers

**Comment by tkknight** [comment]
You could also enable building the docs for each PR, see https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by zklaus** [comment]
If you want, you an add me to the readthedocs project. I might be able to help with this.

**Comment by trexfeathers** [comment]
> If you want, you can add me to the readthedocs project. I might be able to help with this.

Very kind of you @zklaus! We have added you to the maintainers list.
