### ISSUE TITLE
Implement airspeed velocity for monitoring esmf-regrid performance

### ISSUE THREAD

**Issue by jamesp** [SciTools-incubator/iris-esmf-regrid#57]
## ✨ Feature Request

We should add airspeed velocity performance testing to this package so that we can monitor performance improvements over time.

**Comment by trexfeathers** [comment]
Steps:
* Sort out ASV architecture - @trexfeathers working on a PR right now.
* Write first benchmarks - using sample cube-spheres from [SciTools/iris-test-data](https://github.com/SciTools/iris-test-data).
* Joint and separate experiments with:
  * [`asv continuous`](https://asv.readthedocs.io/en/stable/commands.html#asv-continuous)
  * [`asv gh-pages`](https://asv.readthedocs.io/en/stable/commands.html#asv-gh-pages)
* Apply improved knowledge to decisions on:
  * If/how we integrate some/all benchmarks into continuous integration runs.
    Intelligent use of ASV's repeats should _probably_ provide statistical rigour to compensate for possible risks of running on shared architecture.
  * If we run some/all benchmarks overnight on local hardware.
  * What results we publish, and where.

**Comment by trexfeathers** [comment]
We now have a minimum architecture in place ([follow the breadcrumbs from here](https://github.com/SciTools-incubator/iris-esmf-regrid/blob/2456f9b08c9a49cb6cd33555bc5938bdf0edb5be/.cirrus.yml#L112-L139)), which allows for easy addition of new benchmarks, which form part of the standard CI.

There is the outstanding matter of publishing the results - #90 - but this can come later.
