### ISSUE TITLE
Add real integration and gradient field testing

### ISSUE THREAD

**Issue by abooton** [SciTools-incubator/iris-esmf-regrid#61]
## ✨ Feature Request
Add integration testing so that KGO is routinely tested

Integration tests are needed for the following:
* Real data:  From the [iris-test-data repository](https://github.com/SciTools/iris-test-data/tree/master/test_data/NetCDF):
   Testing the regridding of: Tripolar (ORCA) grid, Lambert-Azimutal-Equal-Area, Rotated pole, and ugrid data.  (Tripolar is the most important).

* Gradient field data:  Should enable regidding of different resolutions to be easily assessed

KGO:
* The known-good-output should be checking the exact data values (rather than visualisation of the regridding).
- This could be implemented in line with the methods currently used in Iris.

**Comment by jamesp** [comment]
not stale
